<a href="https://colab.research.google.com/github/kanyaweeud/data_viz_2022/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# โจทย์
Final Exam: งานกลุ่ม Final ที่อาจารย์สุ่มให้

ให้นักศึกษาสร้าง Dashboard แสดงรายงานเกี่ยวกับข้อมูลการตรวจโรค(ov) จาก ไฟล์ alldb.csv และ hospital_list.xlsx

( ดาวน์โหลดจาก https://drive.google.com/drive/folders/1D_Z0fjTki6U6ECbgh2V3wBOSdOXS81YT?fbclid=IwAR3KK7jaRTK1DI3hfBq--qsME4ScgtNdrEbo2yvE2rn08tOTfmXED5kAEB8)

โดยข้อมูลหลักจะอยู่ใน ตาราง alldb.csv 

(ข้อมูลที่สมบูรณ์ที่สามารถนำมาใช้งานได้ต้องมีค่าใน column ต่อไปนี้ดังนี้

user เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)

RowKey เป็น String

date เป็น YYYY-MM-DD

phone เป็น String

site เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)

time เป็น hh-mm-ss

urine มีค่า String

ov เป็นตัวเลข มีค่าตั้งแต่ 0-4 (0 คือไม่พบโรค 1-4

คือพบโรคที่ระดับความรุนแรงต่างๆ)

PartitionKey เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น))


ไฟล์ alldb.csv และ hospital_list.xlsx สามารถถูกเชื่อมโยงกันโดย site ในไฟล์ alldb.csv คือ hcode ในไฟล์ hospital_list.xlsx


โดยข้อมูลสำคัญที่ต้องแสดงคือ

* จำนวนการตรวจในแต่ละพื้นที่ (จังหวัด-อำเภอ ในไฟล์ hospital_list.xlsx) เทียบกับ 
จำนวนที่พบโรค (column ov ในไฟล์ alldb.csv)

* ช่วงเวลาที่ตรวจ (date ในไฟล์ alldb.csv)

* อื่นๆที่นักศึกษาเห็นว่าเป็นประโยชน์ (phone (ชนิดโทรศัพท์ที่ใช้บันทึก), title (คำนำหน้าชื่อ), age (อายุ))

# รายชื่อสมาชิกกลุ่ม unconscious
นางสาวกัญญาวีร์ อุดม 613020610-8

นางสาวรติมา ชินวงษ์ 623020042-0

นายวรเชษฐ์ แก้วเกิด 623020449-0

# การดึงข้อมูลมาจากไดร์ฟ

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
path = '/content/drive/My Drive/DataViz22_data'

In [ ]:
alldb = pd.read_csv(os.path.join(path, 'alldb.csv'), skipinitialspace = True) # skipinitialspace คือ ลบช่องว่างในคอลัมน์ (เว้นวรรค)

In [ ]:
data_file_path = os.path.join(path,'hospital_list.xlsx')  
hospital = pd.read_excel(data_file_path)

In [ ]:
alldb

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

# เลือกข้อมูล

In [ ]:
alldb_01 = alldb[['user','RowKey','date','phone','site','time','urine','ov','PartitionKey','title','age']]
alldb_01

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),0,NaN,data is not completed,data is not completed
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,"iPhone13,4",01234,NaN,NaN,NaN,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),2,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,NaN,bbuogxulur.png,NaN,Samsung SM-A115F,01234,NaN,NaN,NaN,เสรี,data is not completed,data is not completed
40034,NaN,zttpqogiso.png,NaN,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

# เตรียมข้อมูล alldb

## Dropna

In [ ]:
alldb_dp =alldb_01.dropna()
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,data is not completed,data is not completed
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,data is not completed,data is not completed
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,data is not completed,data is not completed
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,นาง,41
...,...,...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001,data is not completed,data is not completed
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001,data is not completed,data is not completed
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx,data is not completed,data is not completed
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy,data is not completed,data is not completed
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz,data is not completed,data is not completed

In [ ]:
print (alldb_dp.dtypes)

user            object
RowKey          object
date            object
phone           object
site            object
time            object
urine           object
ov              object
PartitionKey    object
title           object
age             object
dtype: object

## แก้คำผิด

In [ ]:
alldb_dp['user'].replace({'45-161':'45161','745-61':'74561','71378\n71378':'71378','40591\n40591\n':'40591','17536\n\n17536':'17536',},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

## ต้องการให้ RowKey, phone และ urine เป็น String

In [ ]:
alldb_dp['phone']=alldb_dp['phone'].astype('string')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
alldb_dp['RowKey']=alldb_dp['RowKey'].astype('string')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
alldb_dp['urine']=alldb_dp['urine'].astype('string')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
alldb_dp.dtypes

user            object
RowKey          string
date            object
phone           string
site            object
time            object
urine           string
ov              object
PartitionKey    object
title           object
age             object
dtype: object

In [ ]:
set(alldb_dp['date'])

{'2022-02-15',
 '2022-02-16',
 '2022-02-17',
 '2022-02-18',
 '2022-02-19',
 '2022-02-20',
 '2022-02-21',
 '2022-02-22',
 '2022-02-23',
 '2022-02-24',
 '2022-02-25',
 '2022-02-26',
 '2022-02-27',
 '2022-02-28',
 '2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-05',
 '2022-03-06',
 '2022-03-07',
 '2022-03-08',
 '2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-16',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29',
 '2022-03-30',
 '2022-03-31',
 '2022-04-01',
 '2022-04-02',
 '2022-04-03',
 '2022-04-04',
 '2022-04-05'}

## Formate ให้เป็นวันที่

In [ ]:
alldb_dp['date'] = pd.to_datetime(alldb_dp['date'],format="%Y-%m-%d") 
alldb_dp

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
186,45161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,data is not completed,data is not completed
187,45161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,data is not completed,data is not completed
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,data is not completed,data is not completed
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,นาง,41
...,...,...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001,data is not completed,data is not completed
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001,data is not completed,data is not completed
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx,data is not completed,data is not completed
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy,data is not completed,data is not completed
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz,data is not completed,data is not completed

### date เป็น YYYY-MM-DD แล้ว

## Formate ให้เป็นเวลา

In [ ]:
alldb_dp['time'] = pd.to_datetime(alldb_dp['time'],format='%H:%M%:%S',errors='ignore')
alldb_dp

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
186,45161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,data is not completed,data is not completed
187,45161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,data is not completed,data is not completed
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,data is not completed,data is not completed
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,นาง,41
...,...,...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001,data is not completed,data is not completed
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001,data is not completed,data is not completed
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx,data is not completed,data is not completed
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy,data is not completed,data is not completed
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz,data is not completed,data is not completed

## เปลี่ยนรูปแบบจาก : เป็น -

In [ ]:
alldb_dp['time'] = alldb_dp['time'].replace(':','-', regex=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
set(alldb_dp['time'])

{'15-03-23',
 '23-03-00',
 '15-49-45',
 '09-41-00',
 '09-56-08',
 '14-17-51',
 '13-52-30',
 '20-56-37',
 '17-36-34',
 '09-43-11',
 '10-39-40',
 '11-50-28',
 '15-09-15',
 '16-15-57',
 '14-05-45',
 '14-55-54',
 '09-39-02',
 '09-23-40',
 '12-13-30',
 '12-21-43',
 '13-56-12',
 '14-12-51',
 '09-24-25',
 '11-15-40',
 '19-50-36',
 '10-46-55',
 '13-36-46',
 '11-32-47',
 '15-27-11',
 '15-40-15',
 '17-12-48',
 '09-48-48',
 '14-00-55',
 '15-06-01',
 '08-43-31',
 '09-17-04',
 '13-16-14',
 '12-23-05',
 '14-57-04',
 '15-08-40',
 '10-46-51',
 '15-31-42',
 '10-25-03',
 '09-29-16',
 '11-25-47',
 '16-28-08',
 '11-59-18',
 '10-36-21',
 '15-54-18',
 '17-34-33',
 '14-36-33',
 '12-18-44',
 '14-35-53',
 '15-56-17',
 '17-15-08',
 '13-33-47',
 '13-39-24',
 '17-32-49',
 '11-12-59',
 '15-46-39',
 '17-19-56',
 '15-57-17',
 '17-06-47',
 '09-06-47',
 '10-15-38',
 '15-36-49',
 '16-41-19',
 '10-31-51',
 '16-03-42',
 '13-54-54',
 '17-26-32',
 '13-56-19',
 '10-15-09',
 '11-05-37',
 '11-49-04',
 '11-49-25',
 '11-07-26',
 '10-20-41',
 '10-17-25',
 '14-53-38',
 '08-23-51',
 '16-59-50',
 '14-27-33',
 '12-11-34',
 '13-20-57',
 '09-44-49',
 '16-42-29',
 '16-00-21',
 '13-04-35',
 '15-17-45',
 '16-30-36',
 '08-46-42',
 '11-15-20',
 '10-32-24',
 '10-32-07',
 '15-33-57',
 '09-47-51',
 '11-41-58',
 '13-04-09',
 '15-27-43',
 '10-14-41',
 '12-18-53',
 '11-58-36',
 '11-56-45',
 '15-14-11',
 '15-01-51',
 '09-22-36',
 '09-28-02',
 '19-03-01',
 '19-49-42',
 '14-35-03',
 '12-51-24',
 '12-11-58',
 '18-50-21',
 '15-49-06',
 '16-31-58',
 '09-18-26',
 '11-22-31',
 '16-22-20',
 '15-25-00',
 '15-08-07',
 '18-21-47',
 '09-14-13',
 '11-37-55',
 '13-33-28',
 '14-56-27',
 '15-17-27',
 '12-38-26',
 '16-28-12',
 '17-37-38',
 '14-47-38',
 '10-11-03',
 '11-23-07',
 '12-24-51',
 '16-32-08',
 '17-29-10',
 '16-43-30',
 '12-23-02',
 '13-33-41',
 '12-29-10',
 '13-12-54',
 '11-57-25',
 '22-58-47',
 '11-30-01',
 '15-13-02',
 '10-39-29',
 '15-55-14',
 '10-22-06',
 '17-30-57',
 '11-08-06',
 '10-24-03',
 '21-13-09',
 '15-33-09',
 '15-51-07',
 '13-22-08',
 '15-07-43',
 '14-16-06',
 '11-53-45',
 '09-50-28',
 '14-50-42',
 '13-55-36',
 '15-46-34',
 '14-21-51',
 '11-35-01',
 '11-15-54',
 '15-46-08',
 '14-44-21',
 '12-55-22',
 '15-50-09',
 '15-34-20',
 '11-46-26',
 '16-12-43',
 '12-26-23',
 '11-47-17',
 '09-48-16',
 '16-19-40',
 '15-05-29',
 '09-50-40',
 '15-00-30',
 '12-38-24',
 '18-13-19',
 '15-53-56',
 '14-23-01',
 '11-47-37',
 '11-02-00',
 '10-38-37',
 '15-07-45',
 '11-06-44',
 '14-27-42',
 '14-15-03',
 '10-37-12',
 '09-58-18',
 '12-55-10',
 '10-58-09',
 '12-06-02',
 '11-42-04',
 '10-40-33',
 '10-58-42',
 '09-43-19',
 '19-14-55',
 '11-56-59',
 '09-05-34',
 '14-25-23',
 '11-06-53',
 '10-03-07',
 '11-53-51',
 '14-58-28',
 '12-35-40',
 '14-10-46',
 '18-38-18',
 '09-59-24',
 '13-15-26',
 '11-23-50',
 '21-56-44',
 '09-17-35',
 '12-10-11',
 '10-13-37',
 '17-32-40',
 '15-34-56',
 '11-55-55',
 '12-10-36',
 '16-34-53',
 '22-09-09',
 '13-03-36',
 '14-36-00',
 '09-36-05',
 '09-12-40',
 '13-16-08',
 '13-10-14',
 '15-21-11',
 '10-16-28',
 '10-14-39',
 '13-01-58',
 '21-15-57',
 '16-18-09',
 '15-42-15',
 '11-29-47',
 '16-06-52',
 '14-24-50',
 '12-14-30',
 '15-01-10',
 '14-45-21',
 '14-47-31',
 '15-26-54',
 '09-33-56',
 '15-29-34',
 '15-05-25',
 '22-30-19',
 '16-56-29',
 '11-58-25',
 '10-55-45',
 '10-10-43',
 '10-30-24',
 '12-04-33',
 '10-39-36',
 '13-58-34',
 '15-58-09',
 '13-58-19',
 '11-00-48',
 '14-22-33',
 '18-40-49',
 '14-50-43',
 '15-56-16',
 '16-06-42',
 '12-35-28',
 '16-15-27',
 '13-58-59',
 '08-30-40',
 '13-42-12',
 '11-03-27',
 '15-54-29',
 '15-21-20',
 '11-46-29',
 '09-30-52',
 '15-55-45',
 '12-14-44',
 '10-42-05',
 '11-34-58',
 '16-42-49',
 '12-52-48',
 '14-53-13',
 '12-08-09',
 '14-59-18',
 '14-09-58',
 '16-51-16',
 '10-30-20',
 '13-09-18',
 '09-44-56',
 '09-01-12',
 '11-12-39',
 '12-15-40',
 '11-01-41',
 '14-42-43',
 '14-55-45',
 '12-50-39',
 '10-04-04',
 '10-31-37',
 '08-36-00',
 '10-33-32',
 '18-08-24',
 '14-01-33',
 '12-17-54',
 '14-05-31',
 '16-26-19',
 '11-55-34',
 '14-56-20',
 '15-59-10',
 '16-48-17',
 '10-12-00',
 '16-05-06',
 '14-08-55',
 '12-29-07',
 '14-16-30',
 '09-51-22',
 '12-29-18',
 '13-10-19',
 '13-31-48',
 '09-41-31',
 '10-10-26',
 '12-53-25',
 '11-12-19',
 '17-54-55',
 '09-42-07',
 '10-14-46',
 '10-04-06',
 '16-02-26',
 '16-06-29',
 '10-58-22',
 '19-46-29',
 '10-57-54',
 '11-23-40',
 '22-58-38',
 '15-40-16',
 '12-22-19',
 '20-05-13',
 '15-23-48',
 '10-43-54',
 '14-33-45',
 '19-27-21',
 '17-07-44',
 '11-24-48',
 '16-41-38',
 '12-18-43',
 '16-28-42',
 '16-46-29',
 '11-37-44',
 '09-54-50',
 '11-05-17',
 '12-13-20',
 '11-18-46',
 '11-31-55',
 '10-53-11',
 '11-03-14',
 '14-22-05',
 '10-05-54',
 '11-34-21',
 '08-51-05',
 '09-54-23',
 '14-29-24',
 '10-23-38',
 '14-59-15',
 '15-54-42',
 '09-41-32',
 '12-47-00',
 '13-14-43',
 '21-30-03',
 '10-42-55',
 '15-25-51',
 '11-47-26',
 '10-35-38',
 '13-24-35',
 '08-35-29',
 '09-40-29',
 '10-08-57',
 '08-59-54',
 '11-46-12',
 '16-48-36',
 '11-04-58',
 '12-41-27',
 '11-41-31',
 '12-42-29',
 '17-16-54',
 '11-10-49',
 '10-22-39',
 '10-52-51',
 '12-26-52',
 '11-38-49',
 '16-35-00',
 '09-21-45',
 '14-47-35',
 '09-18-13',
 '13-47-11',
 '15-52-48',
 '08-54-43',
 '16-05-15',
 '15-12-52',
 '14-56-40',
 '10-42-56',
 '10-18-17',
 '21-23-56',
 '15-39-20',
 '09-53-36',
 '15-58-14',
 '11-52-07',
 '12-25-24',
 '13-39-30',
 '12-00-43',
 '12-12-59',
 '14-46-22',
 '10-12-50',
 '10-20-27',
 '15-53-28',
 '11-58-26',
 '15-40-07',
 '07-28-47',
 '11-37-36',
 '15-10-05',
 '16-02-23',
 '10-24-18',
 '10-33-54',
 '09-52-23',
 '13-29-31',
 '11-03-15',
 '19-25-35',
 '09-12-38',
 '15-46-03',
 '18-05-43',
 '09-36-55',
 '08-22-47',
 '15-44-20',
 '09-58-26',
 '11-43-23',
 '10-35-44',
 '13-29-36',
 '20-11-23',
 '14-36-05',
 '10-31-58',
 '20-02-10',
 '11-44-20',
 '16-54-45',
 '11-05-55',
 '09-31-51',
 '15-50-55',
 '15-31-56',
 '17-04-50',
 '15-49-50',
 '16-44-26',
 '09-55-36',
 '09-35-32',
 '13-03-02',
 '20-53-45',
 '14-55-17',
 '14-31-43',
 '13-33-48',
 '11-25-16',
 '16-39-52',
 '13-10-45',
 '09-11-32',
 '17-58-42',
 '15-25-35',
 '10-21-16',
 '14-45-32',
 '13-56-53',
 '12-04-46',
 '09-01-38',
 '10-51-03',
 '10-49-28',
 '11-18-07',
 '17-43-08',
 '11-09-22',
 '15-47-46',
 '11-02-02',
 '18-18-14',
 '11-13-43',
 '10-37-50',
 '20-24-23',
 '08-58-51',
 '16-29-16',
 '10-26-35',
 '21-27-55',
 '09-08-47',
 '11-59-37',
 '12-53-22',
 '12-09-51',
 '17-14-51',
 '11-33-31',
 '09-13-52',
 '12-04-18',
 '10-27-55',
 '14-46-43',
 '08-50-34',
 '16-13-01',
 '11-31-59',
 '18-53-36',
 '10-58-25',
 '11-46-30',
 '11-42-34',
 '08-25-50',
 '16-11-43',
 '11-10-56',
 '16-08-13',
 '12-32-06',
 '10-27-24',
 '12-19-24',
 '11-48-24',
 '10-22-30',
 '20-08-49',
 '16-45-20',
 '15-44-02',
 '11-13-48',
 '13-26-48',
 '11-57-10',
 '16-26-45',
 '16-19-31',
 '11-15-33',
 '15-09-34',
 '09-38-05',
 '12-49-11',
 '16-10-00',
 '09-59-41',
 '13-26-30',
 '10-53-18',
 '08-48-04',
 '16-57-14',
 '12-54-12',
 '09-23-38',
 '12-13-01',
 '11-51-03',
 '10-22-08',
 '10-04-21',
 '10-59-04',
 '18-04-54',
 '10-20-20',
 '16-20-26',
 '16-37-08',
 '10-29-21',
 '14-05-05',
 '17-48-28',
 '08-36-31',
 '13-53-09',
 '15-40-25',
 '17-32-09',
 '09-17-17',
 '14-51-57',
 '16-32-43',
 '10-46-44',
 '12-29-23',
 '11-24-04',
 '14-23-40',
 '10-48-11',
 '22-45-41',
 '09-15-29',
 '11-31-35',
 '09-00-33',
 '13-56-49',
 '14-31-02',
 '15-57-34',
 '10-40-45',
 '17-55-04',
 '14-52-23',
 '09-13-21',
 '11-45-57',
 '11-19-03',
 '11-55-09',
 '09-24-09',
 '11-52-14',
 '11-18-09',
 '13-48-35',
 '09-32-15',
 '13-08-36',
 '17-28-23',
 '16-58-48',
 '15-49-12',
 '16-42-51',
 '09-33-45',
 '14-28-22',
 '19-54-36',
 '15-12-31',
 '10-30-45',
 '13-20-56',
 '14-16-02',
 '11-55-31',
 '10-33-10',
 '14-57-09',
 '19-36-59',
 '11-10-30',
 '12-08-27',
 '18-18-50',
 '11-32-42',
 '14-54-05',
 '16-06-08',
 '10-28-48',
 '11-48-52',
 '12-25-25',
 '12-32-45',
 '16-00-44',
 '09-26-41',
 '17-44-30',
 '14-58-24',
 '12-48-31',
 '10-51-53',
 '14-15-53',
 '14-49-39',
 '11-38-27',
 '11-07-14',
 '15-19-20',
 '16-37-24',
 '14-04-22',
 '11-21-49',
 '09-39-47',
 '12-45-08',
 '09-01-09',
 '13-26-07',
 '11-03-21',
 '16-41-52',
 '16-02-51',
 '16-44-35',
 '13-56-56',
 '21-28-32',
 '14-01-39',
 '15-28-20',
 '14-48-38',
 '10-53-57',
 '10-40-03',
 '13-59-45',
 '18-43-00',
 '13-16-25',
 '19-48-39',
 '11-14-46',
 '13-23-03',
 '14-28-04',
 '11-36-19',
 '14-00-51',
 '15-08-02',
 '15-50-14',
 '10-31-33',
 '11-41-54',
 '10-31-00',
 '17-50-14',
 '12-36-52',
 '12-09-22',
 '16-07-41',
 '12-22-49',
 '09-56-10',
 '13-01-43',
 '11-02-18',
 '13-17-53',
 '11-35-22',
 '12-05-22',
 '17-32-02',
 '11-27-22',
 '13-58-52',
 '13-36-02',
 '15-11-04',
 '08-36-51',
 '14-33-30',
 '13-58-16',
 '14-46-37',
 '12-22-57',
 '13-57-01',
 '11-06-38',
 '12-56-00',
 '14-03-20',
 '13-43-55',
 '14-05-42',
 '10-57-32',
 '09-36-22',
 '17-28-30',
 '09-43-18',
 '13-13-23',
 '10-28-34',
 '09-36-28',
 '15-47-31',
 '12-50-52',
 '15-38-06',
 '10-30-25',
 '18-16-44',
 '12-42-44',
 '16-28-01',
 '20-50-24',
 '16-08-40',
 '14-57-37',
 '13-38-43',
 '10-47-04',
 '15-23-38',
 '09-48-27',
 '18-51-54',
 '12-04-25',
 '11-42-33',
 '15-04-05',
 '14-37-47',
 '10-49-22',
 '11-57-56',
 '15-08-17',
 '09-35-07',
 '14-30-58',
 '14-38-21',
 '13-34-24',
 '12-09-48',
 '10-21-25',
 '11-50-49',
 '10-23-25',
 '11-01-14',
 '21-39-52',
 '11-38-41',
 '10-59-01',
 '11-16-28',
 '12-26-25',
 '09-51-35',
 '17-58-04',
 '10-03-10',
 '09-39-38',
 '10-14-43',
 '12-15-49',
 '17-30-29',
 '10-44-06',
 '14-50-57',
 '11-54-24',
 '09-05-26',
 '11-03-05',
 '15-13-47',
 '22-01-05',
 '11-12-32',
 '16-07-32',
 '09-55-08',
 '19-33-30',
 '15-07-13',
 '15-40-53',
 '13-03-24',
 '10-29-24',
 '10-07-58',
 '13-51-30',
 '21-30-29',
 '11-54-23',
 '13-21-51',
 '11-29-10',
 '17-29-28',
 '13-47-36',
 '09-55-21',
 '15-19-30',
 '11-33-37',
 '13-19-47',
 '13-57-11',
 '10-01-06',
 '12-05-07',
 '10-04-27',
 '16-37-18',
 '12-03-04',
 '13-28-28',
 '11-45-41',
 '11-35-43',
 '19-06-18',
 '16-55-07',
 '16-37-28',
 '14-33-18',
 '15-51-41',
 '10-12-56',
 '10-55-12',
 '10-47-33',
 '10-16-15',
 '13-37-39',
 '13-36-40',
 '22-03-47',
 '12-10-37',
 '11-14-47',
 '11-45-39',
 '15-06-55',
 '17-01-17',
 '13-38-57',
 '20-27-58',
 '08-42-37',
 '11-35-11',
 '11-37-08',
 '12-15-18',
 '10-08-34',
 '10-59-52',
 '12-01-06',
 '10-31-48',
 '16-00-10',
 '11-23-13',
 '14-41-29',
 '15-06-46',
 '09-57-35',
 '10-30-10',
 '14-27-12',
 '15-01-00',
 '15-10-33',
 '11-35-58',
 '13-31-38',
 '08-55-57',
 '10-05-45',
 '14-36-22',
 '15-18-40',
 '12-14-50',
 '16-33-43',
 '16-09-28',
 '13-49-53',
 '10-10-10',
 '13-52-31',
 '16-14-16',
 '11-02-22',
 '23-31-00',
 '11-52-44',
 '12-22-42',
 '12-27-55',
 '10-22-42',
 '20-29-10',
 '16-08-09',
 '13-00-49',
 '14-23-13',
 '14-15-07',
 '13-10-59',
 '15-20-20',
 '17-34-01',
 '10-19-24',
 '15-29-40',
 '12-49-02',
 '10-21-48',
 '15-51-52',
 '12-34-14',
 '11-04-54',
 '13-44-03',
 '11-57-19',
 '09-02-12',
 '14-30-49',
 '17-30-01',
 '17-14-26',
 '15-15-06',
 '15-54-08',
 '09-30-21',
 '14-26-35',
 '17-18-07',
 '16-06-55',
 '12-18-06',
 '15-43-04',
 '16-49-54',
 '15-54-09',
 '14-47-53',
 '11-13-07',
 '10-08-07',
 '14-00-23',
 '16-51-51',
 '10-05-14',
 '14-15-14',
 '08-45-19',
 '16-01-14',
 '08-57-54',
 '15-03-16',
 '15-55-34',
 '10-26-12',
 '10-22-07',
 '12-29-05',
 '19-24-22',
 '15-36-53',
 '12-19-51',
 '11-31-45',
 '13-49-34',
 '11-51-17',
 '09-57-45',
 '16-55-24',
 '16-37-07',
 '14-48-51',
 '11-52-33',
 '10-53-47',
 '14-08-35',
 '14-53-10',
 '11-44-15',
 '10-48-22',
 '17-46-18',
 '13-07-07',
 '09-34-39',
 '14-47-57',
 '09-22-25',
 '12-00-08',
 '11-07-20',
 '10-56-04',
 '13-00-05',
 '15-06-23',
 '11-38-08',
 '17-10-16',
 '14-13-39',
 '16-08-25',
 '19-13-02',
 '11-41-02',
 '15-05-21',
 '17-09-09',
 '12-13-37',
 '09-44-18',
 '09-16-20',
 '15-12-14',
 '20-46-43',
 '17-11-00',
 '14-22-47',
 '10-28-54',
 '12-07-45',
 '11-56-07',
 '12-14-43',
 '16-08-24',
 '12-33-19',
 '09-29-24',
 '15-17-37',
 '14-47-02',
 '10-48-13',
 '11-49-59',
 '12-02-21',
 '12-18-28',
 '16-45-45',
 '17-01-37',
 '15-24-16',
 '10-01-28',
 '20-32-42',
 '14-50-18',
 '11-07-54',
 '14-35-45',
 '15-08-26',
 '11-14-39',
 '11-17-58',
 '15-58-10',
 '14-19-12',
 '16-14-14',
 '18-51-16',
 '19-58-05',
 '15-08-18',
 '12-44-08',
 '12-18-03',
 '14-03-38',
 '14-48-19',
 '09-54-45',
 '14-21-29',
 '13-05-23',
 '10-08-53',
 '14-40-15',
 '08-16-21',
 '12-42-08',
 '13-09-06',
 '09-07-10',
 '09-43-27',
 '15-02-05',
 '09-19-22',
 '09-55-10',
 '21-53-13',
 '17-15-05',
 '10-38-40',
 '11-42-54',
 '09-39-26',
 '12-40-58',
 '16-13-41',
 '11-18-03',
 '18-32-46',
 '12-30-48',
 '14-21-36',
 '13-53-59',
 '12-10-22',
 '19-52-21',
 '10-55-37',
 '09-44-24',
 '21-36-14',
 '11-35-27',
 '16-27-15',
 '13-38-27',
 '12-22-04',
 '16-54-23',
 '10-20-56',
 '10-38-17',
 '15-27-24',
 '12-06-40',
 '13-01-54',
 '14-31-46',
 '14-43-48',
 '13-25-00',
 '09-46-29',
 '13-18-42',
 '13-49-46',
 '09-59-10',
 '11-34-19',
 '12-20-47',
 '10-05-43',
 '16-32-48',
 '13-09-53',
 '10-02-57',
 '08-36-43',
 '15-00-10',
 '09-12-16',
 '10-22-35',
 '11-56-01',
 '18-00-51',
 '15-51-55',
 '14-16-25',
 '12-18-11',
 '10-51-30',
 '14-59-36',
 '16-38-39',
 '14-20-51',
 '13-59-38',
 '18-16-10',
 '16-57-24',
 '09-41-05',
 '17-21-51',
 '10-45-04',
 '14-04-49',
 ...}

### time เป็น hh-mm-ss แล้ว

# ทำให้คอลัมน์ user, site, ov และ PartitionKey มี 5 หลัก

In [ ]:
US=list() # สร้าง list ว่าง
for each_row in alldb_dp.iterrows(): #.iterrows เพื่อให้เราสามารถ Loop และเข้าถึงข้อมูลทีละ Row ได้เลย ผ่าน Function ที่ชื่อว่า Iterrows
    if len(str(each_row[1]['user']))== 5 : # len(str เอา str ที่มี 5 หลัก
       if str(each_row[1]['user']) <= '99999' : # เงื่อนไขเอาที่มีค่าน้อยกว่าเท่ากับ 99999
          US.append(True)  # ถ้าตรงเงื่อนไขก็จะเอาที่ตรงเงื่อนไขมาต่อกัน
       else: 
          US.append(False)  
    else: 
          US.append(False) # ถ้าไม่ตรงเงื่อนไขก็จะเอาออกไป
alldb_dp = alldb_dp[US]
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
186,45161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09-45-28,ปกติ (เหลืองใส),0,0-1528,data is not completed,data is not completed
187,45161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10-06-45,ปกติ (เหลืองใส),0,0-1544,data is not completed,data is not completed
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0,0000,data is not completed,data is not completed
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,นาง,41
...,...,...,...,...,...,...,...,...,...,...,...
39722,76331,bbrbiwclgv.png,2022-02-23,Samsung SM-G965U,05258,14-05-25,ปกติ (เหลืองใส),0,61,data is not completed,data is not completed
39782,76331,lzzsckyyqs.png,2022-02-23,Samsung SM-G965U,05258,14-42-45,ปกติ (เหลืองใส),0,89,data is not completed,data is not completed
39791,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15-32-53,ปกติ (เหลืองใส),1,92,data is not completed,data is not completed
39794,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14-31-01,ปกติ (เหลืองใส),2,976,data is not completed,data is not completed
39795,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14-30-21,ปกติ (เหลืองใส),2,983,data is not completed,data is not completed

In [ ]:
SI=list() 
for each_row in alldb_dp.iterrows(): 
    if len(str(each_row[1]['site']))== 5 : 
        if str(each_row[1]['site']) <= '99999' : 
          SI.append(True) 
        else: 
          SI.append(False)  
    else: 
          SI.append(False) 
alldb_dp = alldb_dp[SI]
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
186,45161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09-45-28,ปกติ (เหลืองใส),0,0-1528,data is not completed,data is not completed
187,45161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10-06-45,ปกติ (เหลืองใส),0,0-1544,data is not completed,data is not completed
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0,0000,data is not completed,data is not completed
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,นาง,41
...,...,...,...,...,...,...,...,...,...,...,...
39722,76331,bbrbiwclgv.png,2022-02-23,Samsung SM-G965U,05258,14-05-25,ปกติ (เหลืองใส),0,61,data is not completed,data is not completed
39782,76331,lzzsckyyqs.png,2022-02-23,Samsung SM-G965U,05258,14-42-45,ปกติ (เหลืองใส),0,89,data is not completed,data is not completed
39791,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15-32-53,ปกติ (เหลืองใส),1,92,data is not completed,data is not completed
39794,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14-31-01,ปกติ (เหลืองใส),2,976,data is not completed,data is not completed
39795,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14-30-21,ปกติ (เหลืองใส),2,983,data is not completed,data is not completed

In [ ]:
PK=list() 
for each_row in alldb_dp.iterrows(): 
    if len(str(each_row[1]['PartitionKey']))== 5 : 
        if str(each_row[1]['PartitionKey']) <= '99999' : 
          PK.append(True) 
        else: 
          PK.append(False)  
    else: 
          PK.append(False) 
alldb_dp = alldb_dp[PK]
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,นางสาว,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,นาง,41
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,นาง,55
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,นาย,66
195,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,นางสาว,50
...,...,...,...,...,...,...,...,...,...,...,...
39416,26462,ieotqfnqcq.png,2022-03-22,Vivo 1920,11069,14-03-12,ปกติ (เหลืองใส),1,11003,นางสาว,33
39417,26462,cywpeqziic.png,2022-03-21,Vivo 1920,11069,13-59-04,ปกติ (เหลืองใส),2,11005,นาย,28
39418,26462,65DE7A37-62D2-4B7F-A494-89A89D5594A7,2022-03-22,"iPhone13,4",11069,13-41-47,ปกติ (เหลืองใส),2,11006,นาง,72
39419,26462,85F0F443-D3B6-40DD-BD69-81C8D696E0DC,2022-03-21,"iPhone13,4",11069,14-17-46,ปกติ (เหลืองใส),0,11007,นาง,48
39420,26462,vdxxgljykj.png,2022-03-21,Vivo V2050,11069,10-54-49,"ปกติ (เหลืองใส), ใส่เป็นน้ำเปล่า",1,11008,นาย,36

In [ ]:
set(alldb_dp['user'])

{'69428',
 '26540',
 '41951',
 '54974',
 '87468',
 '27802',
 '48956',
 '02728',
 '70455',
 '46341',
 '37228',
 '85493',
 '10348',
 '32200',
 '66780',
 '00265',
 '31551',
 '20827',
 '73557',
 '50172',
 '30016',
 '89801',
 '19180',
 '82054',
 '15046',
 '63767',
 '00270',
 '47146',
 '61359',
 '43431',
 '67280',
 '12576',
 '86299',
 '59305',
 '01428',
 '25219',
 '44509',
 '84005',
 '00134',
 '34705',
 '89576',
 '08370',
 '18527',
 '87029',
 '00211',
 '84187',
 '22377',
 '31762',
 '14106',
 '59266',
 '63200',
 '02087',
 '62061',
 '86588',
 '19671',
 '74367',
 '36358',
 '37259',
 '37915',
 '05063',
 '00190',
 '12041',
 '10105',
 '25943',
 '00183',
 '83733',
 '08773',
 '50471',
 '09226',
 '65775',
 '71872',
 '66191',
 '63471',
 '02604',
 '76331',
 '45701',
 '80382',
 '82685',
 '00170',
 '10905',
 '21751',
 '63799',
 '15971',
 '48069',
 '51892',
 '42468',
 '78494',
 '84375',
 '44364',
 '16428',
 '03562',
 '69566',
 '01721',
 '09259',
 '52921',
 '41042',
 '33081',
 '29875',
 '48908',
 '65555',
 '62261',
 '46520',
 '00151',
 '39079',
 '17916',
 '50284',
 '10194',
 '53356',
 '70948',
 '64520',
 '53041',
 '12003',
 '23012',
 '63381',
 '51689',
 '18865',
 '98290',
 '95609',
 '00213',
 '00043',
 '14491',
 '31811',
 '99011',
 '51474',
 '89470',
 '00002',
 '84409',
 '24404',
 '05113',
 '55239',
 '97013',
 '01730',
 '02639',
 '75347',
 '50004',
 '00071',
 '95161',
 '49863',
 '31792',
 '00051',
 '47844',
 '00009',
 '05291',
 '28890',
 '71791',
 '00272',
 '00137',
 '53333',
 '25829',
 '22680',
 '05242',
 '31534',
 '25683',
 '95291',
 '00267',
 '01467',
 '30121',
 '92220',
 '97016',
 '87218',
 '37691',
 '25837',
 '05232',
 '00114',
 '77509',
 '16174',
 '39959',
 '73233',
 '99245',
 '09315',
 '40828',
 '03381',
 '93020',
 '50332',
 '38463',
 '38778',
 '37732',
 '02784',
 '80979',
 '84495',
 '00147',
 '79525',
 '00122',
 '00214',
 '00941',
 '05961',
 '52227',
 '60847',
 '14835',
 '75251',
 '74394',
 '00755',
 '76246',
 '73496',
 '00203',
 '37551',
 '51310',
 '93307',
 '05182',
 '59423',
 '05151',
 '00024',
 '69789',
 '09820',
 '47135',
 '28402',
 '61182',
 '46415',
 '48368',
 '12839',
 '75579',
 '32625',
 '28961',
 '65995',
 '52147',
 '81095',
 '82894',
 '19575',
 '26082',
 '98245',
 '12605',
 '38518',
 '82777',
 '28348',
 '51973',
 '08741',
 '01008',
 '65509',
 '27658',
 '00357',
 '80374',
 '76339',
 '62941',
 '33103',
 '33643',
 '89475',
 '74432',
 '61044',
 '65656',
 '09269',
 '25083',
 '18873',
 '54100',
 '00133',
 '26651',
 '53188',
 '00059',
 '25179',
 '47567',
 '04402',
 '59721',
 '31208',
 '25593',
 '09188',
 '32387',
 '27529',
 '99376',
 '02853',
 '52066',
 '61552',
 '96730',
 '76105',
 '03087',
 '80847',
 '97860',
 '94558',
 '00235',
 '10405',
 '65075',
 '26604',
 '71417',
 '03649',
 '65632',
 '18737',
 '65390',
 '00404',
 '73946',
 '00409',
 '58814',
 '33664',
 '56326',
 '55354',
 '10460',
 '08971',
 '53980',
 '16754',
 '59476',
 '24612',
 '23675',
 '55692',
 '36001',
 '61806',
 '88315',
 '20454',
 '47593',
 '52830',
 '65675',
 '00208',
 '00032',
 '00902',
 '30767',
 '85737',
 '13073',
 '05272',
 '29379',
 '49424',
 '09902',
 '32816',
 '75921',
 '10724',
 '65254',
 '81529',
 '05663',
 '66381',
 '66082',
 '55865',
 '11611',
 '24563',
 '18524',
 '26442',
 '43068',
 '98530',
 '14767',
 '39593',
 '84935',
 '11887',
 '01850',
 '09529',
 '45531',
 '13978',
 '42380',
 '00303',
 '85504',
 '84196',
 '27484',
 '31086',
 '05358',
 '71891',
 '50951',
 '60181',
 '47607',
 '77665',
 '97831',
 '17055',
 '77254',
 '02962',
 '37186',
 '05849',
 '30977',
 '62687',
 '46783',
 '61746',
 '52481',
 '11159',
 '13312',
 '46627',
 '49659',
 '25804',
 '52219',
 '00302',
 '37645',
 '94392',
 '05047',
 '03338',
 '26990',
 '88337',
 '00566',
 '63306',
 '04055',
 '31062',
 '19675',
 '55430',
 '66708',
 '85934',
 '19237',
 '73302',
 '18733',
 '41026',
 '43657',
 '85379',
 '54923',
 '45641',
 '29094',
 '96292',
 '63018',
 '84374',
 '07331',
 '00126',
 '19632',
 '00348',
 '05069',
 '55911',
 '23738',
 '00019',
 '59181',
 '00031',
 '00054',
 '47605',
 '00159',
 '69556',
 '33100',
 '37728',
 '70290',
 '83662',
 '00215',
 '70492',
 '06964',
 '02075',
 '26043',
 '16675',
 '72988',
 '47810',
 '49901',
 '83257',
 '96061',
 '57398',
 '51205',
 '81537',
 '00202',
 '00268',
 '25478',
 '51065',
 '35512',
 '47623',
 '00035',
 '32999',
 '00237',
 '01431',
 '81724',
 '94295',
 '26459',
 '93726',
 '53616',
 '00013',
 '00049',
 '91645',
 '00117',
 '46767',
 '00756',
 '22545',
 '21378',
 '30067',
 '84276',
 '38121',
 '90257',
 '54614',
 '26957',
 '26989',
 '61121',
 '54538',
 '12044',
 '10518',
 '37151',
 '39342',
 '63098',
 '02897',
 '00288',
 '45047',
 '72186',
 '12023',
 '61587',
 '50900',
 '00221',
 '81570',
 '31577',
 '11215',
 '36385',
 '22478',
 '45563',
 '33869',
 '17191',
 '62440',
 '75126',
 '37231',
 '00293',
 '68112',
 '51653',
 '18008',
 '96706',
 '47858',
 '77743',
 '98509',
 '77587',
 '44018',
 '78054',
 '06924',
 '23630',
 '88459',
 '79834',
 '91125',
 '00298',
 '26773',
 '81621',
 '36692',
 '99771',
 '22804',
 '19364',
 '94454',
 '70490',
 '00165',
 '22692',
 '22456',
 '54427',
 '60581',
 '66501',
 '66205',
 '49413',
 '18331',
 '16112',
 '00010',
 '94019',
 '39537',
 '21688',
 '63323',
 '24501',
 '29000',
 '27732',
 '00079',
 '19211',
 '46622',
 '29514',
 '81472',
 '00304',
 '67409',
 '94414',
 '65733',
 '00274',
 '89290',
 '28627',
 '66771',
 '81065',
 '00345',
 '00217',
 '67972',
 '49387',
 '94279',
 '08011',
 '46662',
 '85433',
 '23796',
 '00022',
 '84459',
 '30059',
 '73419',
 '31133',
 '29611',
 '34988',
 '17938',
 '17777',
 '40553',
 '00044',
 '90604',
 '54544',
 '00324',
 '02579',
 '45593',
 '14255',
 '32581',
 '73636',
 '00150',
 '74861',
 '71503',
 '94601',
 '72938',
 '20380',
 '11198',
 '83303',
 '63312',
 '53510',
 '94881',
 '80734',
 '76486',
 '11387',
 '03736',
 '78257',
 '47061',
 '00910',
 '39764',
 '60909',
 '02547',
 '28186',
 '46960',
 '91209',
 '19756',
 '78673',
 '04221',
 '89381',
 '00132',
 '87541',
 '50577',
 '00017',
 '19322',
 '14189',
 '44201',
 '93671',
 '61419',
 '82951',
 '13824',
 '89609',
 '19800',
 '00050',
 '03831',
 '87181',
 '41061',
 '00158',
 '19250',
 '34409',
 '61591',
 '16214',
 '55236',
 '56044',
 '15801',
 '02862',
 '01461',
 '71805',
 '03731',
 '86721',
 '48016',
 '36994',
 '25331',
 '39448',
 '73772',
 '04854',
 '04387',
 '10120',
 '38771',
 '49596',
 '00034',
 '95927',
 '00781',
 '49178',
 '40035',
 '19411',
 '21831',
 '18318',
 '00188',
 '28593',
 '45884',
 '00279',
 '75838',
 '50291',
 '97913',
 '00226',
 '38822',
 '00341',
 '78486',
 '18393',
 '26440',
 '34331',
 '27046',
 '82211',
 '86758',
 '79001',
 '96760',
 '89081',
 '65854',
 '32468',
 '28399',
 '32891',
 '70409',
 '02128',
 '79620',
 '00065',
 '32077',
 '12413',
 '00046',
 '19855',
 '00048',
 '00301',
 '69911',
 '88708',
 '00130',
 '49634',
 '00153',
 '00216',
 '80481',
 '18025',
 '84768',
 '00273',
 '20061',
 '20690',
 '07573',
 '90612',
 '38614',
 '00162',
 '74375',
 '21955',
 '00074',
 '28977',
 '17560',
 '43791',
 '42120',
 '02825',
 '94406',
 '00030',
 '65301',
 '00624',
 '68081',
 '47950',
 '81057',
 '06079',
 '25221',
 '34585',
 '39524',
 '50727',
 '66155',
 '64503',
 '84493',
 '32948',
 '73000',
 '77782',
 '63429',
 '26647',
 '74782',
 '19762',
 '11007',
 '70370',
 '00155',
 '92893',
 '29502',
 '83943',
 '64385',
 '00040',
 '98474',
 '92948',
 '11727',
 '50756',
 '00166',
 '63091',
 '60250',
 '55075',
 '23889',
 '29417',
 '25403',
 '80463',
 '00138',
 '00233',
 '05219',
 '09617',
 '85989',
 '35139',
 '16783',
 '51241',
 '73876',
 '74289',
 '44845',
 '31994',
 '14771',
 '28992',
 '20215',
 '27589',
 '25659',
 '10264',
 '47938',
 '76851',
 '94087',
 '22635',
 '54458',
 '92648',
 '12378',
 '97281',
 '00204',
 '91917',
 '97505',
 '80880',
 '00112',
 '00001',
 '95104',
 '42453',
 '83377',
 '03217',
 '89681',
 '02663',
 '03263',
 '00115',
 '58271',
 '87394',
 '00196',
 '94538',
 '67094',
 '95821',
 '99734',
 '30431',
 '11808',
 '00352',
 '00152',
 '02693',
 '86133',
 '22542',
 '38727',
 '70957',
 '75910',
 '03431',
 '17790',
 '31143',
 '15731',
 '42228',
 '33251',
 '38381',
 '74069',
 '45924',
 '05019',
 '14037',
 '31428',
 '00154',
 '00320',
 '97255',
 '02990',
 '82277',
 '61218',
 '20847',
 '54468',
 '80673',
 '65321',
 '92120',
 '24846',
 '39726',
 '96099',
 '76803',
 '73158',
 '17564',
 '04857',
 '50276',
 '00271',
 '42098',
 '94150',
 '52350',
 '97461',
 '00014',
 '00042',
 '06855',
 '45729',
 '71327',
 '61265',
 '33503',
 '48298',
 '00116',
 '61486',
 '25466',
 '31879',
 '95978',
 '33237',
 '87697',
 '79322',
 '37408',
 '32666',
 '18892',
 '96786',
 '00052',
 '23958',
 '00296',
 '86050',
 '00169',
 '00565',
 '49268',
 '27503',
 '50624',
 '14801',
 '58718',
 '18954',
 '47602',
 '57228',
 '11522',
 '33171',
 '72364',
 '03558',
 '03500',
 '69091',
 '00206',
 '11282',
 '11864',
 '73375',
 '00018',
 '22119',
 '29271',
 '29025',
 '68856',
 '75841',
 '02518',
 '97308',
 '22099',
 '02759',
 '34317',
 '85753',
 '04255',
 '45914',
 '62059',
 '03359',
 '58845',
 '00027',
 '00004',
 '55806',
 '14360',
 '64810',
 '63274',
 '88135',
 '96349',
 '00313',
 '21860',
 '10695',
 '27129',
 '79493',
 '20304',
 '29118',
 '44888',
 '02263',
 '52520',
 '09582',
 '32914',
 '80289',
 '62459',
 '40059',
 '06268',
 '93189',
 '87067',
 '86542',
 '24375',
 '63068',
 '39802',
 '00295',
 '32082',
 '53076',
 '93884',
 '93991',
 '14390',
 '51501',
 '44199',
 '86474',
 '50349',
 '76475',
 '12015',
 '39539',
 '38547',
 '00076',
 '35942',
 '99475',
 '01883',
 '16529',
 '00748',
 '00078',
 '90609',
 '25199',
 '17132',
 '31619',
 '51568',
 '04325',
 '35888',
 '12561',
 '03169',
 '01651',
 '50047',
 '58668',
 '68006',
 '03617',
 '51403',
 '89837',
 '67093',
 '14291',
 '55300',
 '12022',
 '23338',
 '00209',
 '58196',
 '77670',
 '68768',
 '45881',
 '26574',
 '77567',
 '72486',
 '92691',
 '18513',
 '14884',
 '00131',
 '08602',
 '46643',
 '96771',
 '48710',
 '89493',
 '86547',
 '00351',
 '00023',
 '85444',
 '86113',
 '47933',
 '45825',
 '08734',
 '00039',
 '00028',
 '51795',
 '86601',
 '05507',
 '03308',
 '24986',
 '01882',
 '00053',
 '00136',
 '05374',
 '23058',
 '88973',
 '24468',
 ...}

## แก้คำผิดบางส่วนเผื่อมีข้อมูลตกหล่น

In [ ]:
alldb_dp['user'].replace({'3450101325119':None,
'34501009308':None,
'71378\n71378':'71378',
'7197':None,
'745-61':'74561',
'3450100810285':None,
'11111111':None,
'3450100805222':None,
'3450101556129':None,
'3450101325593':None,
'4':None,
'6724100235':None,
'17536\n\n17536':'17536',
'3450101229373':None,
'3451100324624':None,
'40591\n40591\n':'40591',
'6724-':None,
'3450101536268':None,
'3450100543961':None,
'3451100451758':None,
'5600190011969':None,
'3451400598487':None,
'3':None,
'3400900747146':None,
'5450100026807':None,
'5799':None,
'3451100141252':None,
'5450500072920':None,
'3450101323370':None,
'45-161':None,
'3451100241281':None,
'3451100324713':None,
'3450101514299':None,
'3451100451251':None,
'1450700099250':None,
'3450100836420':None,
'3450500541443':None,
'5451100055352':None,
'3451100146637':None,
'3450100940367':None,
'3460500500020':None,
'3450101325097':None,
'3459900286317':None,
'3451100150251':None,
'3450101576642':None,
'  67241\n':'67241'
},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [ ]:
set(alldb_dp['site'])

{'00027',
 '00040',
 '00513',
 '00579',
 '00580',
 '02759',
 '03432',
 '03626',
 '04275',
 '04279',
 '04280',
 '04281',
 '04302',
 '04312',
 '04313',
 '04321',
 '04322',
 '04326',
 '04337',
 '04347',
 '04349',
 '04351',
 '04352',
 '04355',
 '04374',
 '04376',
 '04380',
 '04384',
 '04387',
 '04388',
 '04390',
 '04391',
 '04396',
 '04399',
 '04401',
 '04402',
 '04403',
 '04404',
 '04405',
 '04406',
 '04407',
 '04408',
 '04433',
 '04434',
 '04435',
 '04436',
 '04437',
 '04438',
 '04441',
 '04443',
 '04455',
 '04456',
 '04457',
 '04458',
 '04475',
 '04478',
 '04558',
 '04936',
 '04968',
 '04970',
 '04971',
 '04973',
 '04974',
 '04977',
 '04980',
 '04981',
 '04982',
 '04983',
 '04984',
 '04985',
 '04986',
 '04989',
 '04990',
 '04992',
 '04993',
 '04994',
 '04995',
 '04996',
 '04997',
 '04999',
 '05000',
 '05001',
 '05002',
 '05003',
 '05004',
 '05005',
 '05006',
 '05007',
 '05008',
 '05009',
 '05010',
 '05011',
 '05012',
 '05013',
 '05015',
 '05016',
 '05019',
 '05021',
 '05022',
 '05023',
 '05024',
 '05025',
 '05026',
 '05027',
 '05028',
 '05029',
 '05032',
 '05033',
 '05034',
 '05035',
 '05038',
 '05040',
 '05042',
 '05044',
 '05045',
 '05047',
 '05048',
 '05049',
 '05052',
 '05054',
 '05055',
 '05058',
 '05059',
 '05060',
 '05061',
 '05062',
 '05063',
 '05064',
 '05065',
 '05066',
 '05067',
 '05068',
 '05069',
 '05072',
 '05074',
 '05075',
 '05077',
 '05080',
 '05081',
 '05082',
 '05083',
 '05084',
 '05086',
 '05087',
 '05088',
 '05090',
 '05091',
 '05094',
 '05097',
 '05098',
 '05100',
 '05101',
 '05102',
 '05103',
 '05107',
 '05111',
 '05112',
 '05113',
 '05115',
 '05116',
 '05117',
 '05119',
 '05120',
 '05123',
 '05125',
 '05126',
 '05128',
 '05129',
 '05131',
 '05132',
 '05133',
 '05135',
 '05136',
 '05141',
 '05143',
 '05144',
 '05146',
 '05147',
 '05152',
 '05154',
 '05157',
 '05158',
 '05162',
 '05166',
 '05172',
 '05173',
 '05175',
 '05177',
 '05178',
 '05180',
 '05181',
 '05182',
 '05185',
 '05187',
 '05188',
 '05192',
 '05193',
 '05194',
 '05195',
 '05196',
 '05198',
 '05200',
 '05203',
 '05205',
 '05207',
 '05210',
 '05211',
 '05213',
 '05214',
 '05215',
 '05219',
 '05220',
 '05222',
 '05223',
 '05224',
 '05225',
 '05226',
 '05228',
 '05229',
 '05233',
 '05236',
 '05237',
 '05238',
 '05240',
 '05242',
 '05244',
 '05245',
 '05246',
 '05247',
 '05248',
 '05249',
 '05250',
 '05251',
 '05252',
 '05253',
 '05254',
 '05256',
 '05257',
 '05258',
 '05259',
 '05260',
 '05261',
 '05264',
 '05265',
 '05291',
 '05298',
 '05300',
 '05304',
 '05310',
 '05311',
 '05312',
 '05313',
 '05314',
 '05315',
 '05316',
 '05322',
 '05323',
 '05324',
 '05325',
 '05327',
 '05328',
 '05332',
 '05335',
 '05337',
 '05338',
 '05339',
 '05340',
 '05343',
 '05344',
 '05345',
 '05346',
 '05349',
 '05350',
 '05351',
 '05352',
 '05354',
 '05355',
 '05356',
 '05357',
 '05358',
 '05359',
 '05360',
 '05361',
 '05363',
 '05365',
 '05366',
 '05367',
 '05368',
 '05370',
 '05371',
 '05373',
 '05378',
 '05386',
 '05391',
 '05392',
 '05393',
 '05394',
 '05395',
 '05396',
 '05413',
 '05414',
 '05415',
 '05416',
 '05418',
 '05419',
 '05422',
 '05423',
 '05424',
 '05425',
 '05428',
 '05431',
 '05432',
 '05433',
 '05434',
 '05435',
 '05436',
 '05437',
 '05439',
 '05440',
 '05441',
 '05442',
 '05541',
 '06238',
 '06251',
 '06253',
 '06254',
 '06255',
 '06256',
 '06257',
 '06259',
 '06260',
 '06261',
 '06263',
 '06265',
 '06267',
 '06268',
 '06270',
 '06271',
 '06272',
 '06273',
 '06274',
 '06275',
 '06276',
 '06277',
 '06278',
 '06279',
 '06280',
 '06281',
 '06282',
 '06283',
 '06285',
 '06286',
 '06287',
 '06288',
 '06289',
 '06290',
 '06291',
 '06292',
 '06293',
 '06294',
 '06295',
 '06296',
 '06297',
 '06298',
 '06299',
 '06300',
 '06301',
 '06302',
 '06307',
 '06308',
 '06309',
 '06310',
 '06311',
 '06312',
 '06314',
 '06315',
 '06316',
 '06318',
 '06319',
 '06320',
 '06321',
 '06322',
 '06323',
 '06324',
 '06325',
 '06326',
 '06327',
 '06328',
 '06329',
 '06330',
 '06331',
 '06332',
 '06333',
 '06334',
 '10360',
 '10673',
 '11010',
 '11055',
 '11056',
 '11057',
 '11059',
 '11060',
 '11066',
 '11069',
 '11070',
 '11072',
 '11073',
 '11084',
 '11088',
 '11158',
 '11159',
 '11160',
 '11161',
 '11163',
 '11164',
 '11165',
 '11748',
 '11749',
 '13777',
 '13937',
 '13941',
 '13943',
 '13944',
 '13946',
 '13947',
 '13948',
 '13949',
 '13952',
 '13953',
 '13954',
 '13955',
 '13962',
 '13963',
 '13966',
 '13984',
 '14005',
 '14007',
 '14280',
 '14284',
 '14843',
 '24650',
 '27988',
 '27990',
 '28017',
 '99795'}

In [ ]:
alldb_dp['site'].replace({' 0502':None,
'05250\n':'05250',
'05350ยอ':'05350',
'13943\n\n':'13943',
'043.1':None
},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [ ]:
set(alldb_dp['PartitionKey'])

{'01018',
 '02029',
 '00869',
 '04020',
 '01754',
 '01798',
 '02058',
 '00777',
 '01839',
 '02507',
 '02728',
 '00728',
 '02802',
 '06062',
 '00658',
 '01006',
 '01838',
 '00977',
 '01500',
 '00265',
 '00915',
 '02524',
 '01554',
 '01391',
 '02155',
 '02327',
 '02671',
 '01194',
 '02085',
 '02770',
 '08968',
 '04094',
 '02558',
 '06312',
 '01739',
 '01881',
 '02133',
 '02422',
 '03434',
 '04019',
 '00479',
 '06013',
 '01568',
 '04691',
 '10971',
 '01571',
 '01538',
 '01092',
 '02144',
 '01694',
 '02366',
 '00061',
 '00270',
 '02173',
 '03183',
 '02424',
 '04666',
 '08902',
 '01802',
 '00442',
 '05255',
 '03329',
 '01428',
 '01886',
 '02107',
 '01363',
 '01609',
 '00070',
 '08421',
 '01212',
 '00134',
 '08928',
 '05982',
 '10961',
 '04672',
 '01855',
 '02007',
 '00719',
 '02752',
 '00211',
 '02523',
 '01962',
 '03998',
 '01688',
 '01625',
 '02741',
 '01707',
 '01974',
 '10991',
 '00393',
 '00830',
 '02516',
 '02077',
 '02006',
 '00057',
 '00917',
 '01782',
 '02200',
 '03127',
 '01335',
 '01473',
 '09017',
 '01380',
 '04811',
 '01863',
 '02544',
 '02926',
 '02953',
 '05350',
 '04180',
 '01188',
 '00402',
 '00190',
 '02070',
 '00903',
 '08519',
 '01724',
 '00183',
 '04694',
 '00374',
 '00264',
 '01405',
 '02585',
 '08954',
 '09040',
 '03378',
 '00551',
 '03112',
 '02604',
 '05382',
 '01413',
 '00886',
 '00613',
 '01392',
 '01276',
 '02534',
 '01337',
 '00170',
 '10973',
 '00994',
 '01580',
 '00942',
 '10984',
 '00471',
 '00882',
 '01645',
 '03961',
 '03068',
 '02395',
 '02602',
 '00381',
 '01079',
 '01306',
 '01305',
 '08963',
 '01299',
 '02989',
 '00463',
 '02405',
 '01399',
 '00580',
 '01603',
 '03132',
 '00483',
 '01163',
 '04684',
 '01108',
 '01880',
 '00693',
 '04717',
 '08996',
 '01721',
 '01191',
 '02117',
 '02846',
 '01352',
 '06023',
 '01148',
 '03538',
 '00504',
 '00101',
 '01447',
 '02538',
 '02630',
 '00085',
 '01167',
 '08913',
 '01368',
 '02360',
 '05133',
 '00151',
 '04104',
 '02442',
 '03358',
 '01943',
 '02861',
 '00444',
 '00771',
 '03508',
 '04654',
 '00726',
 '01490',
 '04073',
 '00955',
 '00549',
 '00356',
 '03189',
 '02731',
 '00839',
 '00325',
 '08937',
 '02236',
 '01548',
 '01551',
 '02490',
 '02813',
 '01671',
 '00478',
 '01434',
 '02598',
 '05139',
 '00576',
 '01304',
 '02030',
 '04008',
 '03433',
 '01166',
 '00275',
 '01673',
 '08957',
 '00879',
 '01229',
 '00259',
 '00213',
 '00043',
 '01906',
 '02492',
 '06060',
 '01051',
 '02136',
 '00919',
 '00093',
 '00370',
 '01113',
 '01240',
 '02420',
 '00228',
 '00954',
 '01747',
 '00507',
 '02249',
 '00002',
 '00907',
 '08918',
 '05113',
 '02351',
 '00741',
 '00983',
 '00556',
 '01366',
 '00844',
 '05238',
 '02639',
 '00885',
 '00832',
 '01373',
 '02967',
 '00493',
 '00685',
 '00071',
 '01930',
 '03140',
 '09001',
 '04662',
 '09028',
 '01374',
 '05959',
 '00749',
 '00051',
 '00255',
 '00009',
 '00627',
 '04039',
 '00272',
 '00416',
 '00585',
 '00834',
 '01558',
 '00137',
 '05093',
 '00979',
 '00503',
 '02210',
 '01104',
 '00871',
 '01331',
 '02943',
 '10997',
 '02019',
 '05097',
 '00739',
 '00403',
 '01928',
 '03141',
 '01099',
 '03156',
 '03269',
 '00267',
 '04754',
 '01184',
 '01467',
 '01236',
 '02048',
 '04655',
 '00999',
 '01854',
 '01531',
 '02708',
 '04693',
 '05977',
 '01204',
 '01660',
 '00443',
 '05232',
 '00842',
 '00114',
 '01205',
 '04015',
 '08067',
 '01176',
 '02958',
 '00097',
 '02845',
 '01804',
 '01141',
 '08929',
 '00971',
 '00496',
 '01581',
 '02043',
 '02807',
 '03545',
 '05362',
 '00846',
 '00604',
 '02799',
 '01750',
 '05995',
 '11006',
 '00570',
 '00389',
 '01440',
 '00185',
 '03381',
 '05308',
 '01576',
 '01407',
 '01823',
 '05967',
 '02784',
 '02756',
 '01336',
 '01977',
 '01953',
 '00147',
 '04649',
 '04165',
 '03072',
 '00369',
 '00122',
 '01282',
 '00214',
 '01250',
 '02262',
 '02841',
 '02034',
 '00941',
 '03092',
 '01752',
 '05961',
 '03155',
 '01071',
 '00672',
 '03078',
 '00816',
 '01123',
 '00418',
 '01058',
 '00755',
 '00203',
 '03521',
 '05962',
 '02773',
 '01935',
 '02279',
 '00262',
 '02688',
 '03211',
 '01220',
 '00024',
 '00801',
 '05235',
 '03121',
 '01393',
 '00227',
 '00095',
 '02036',
 '00526',
 '04186',
 '01387',
 '00674',
 '00724',
 '03711',
 '00425',
 '01472',
 '01617',
 '00518',
 '00614',
 '00450',
 '02592',
 '03266',
 '08934',
 '01332',
 '01249',
 '02783',
 '01029',
 '01454',
 '01131',
 '04974',
 '00257',
 '01975',
 '01417',
 '00072',
 '02033',
 '03039',
 '00554',
 '01008',
 '00695',
 '01007',
 '01316',
 '04511',
 '01489',
 '00564',
 '09024',
 '00357',
 '01519',
 '01853',
 '01385',
 '01769',
 '00555',
 '04692',
 '00359',
 '01310',
 '01661',
 '03593',
 '01493',
 '08976',
 '03181',
 '00920',
 '01654',
 '00690',
 '00490',
 '01432',
 '01295',
 '02887',
 '05983',
 '01641',
 '03437',
 '00981',
 '06015',
 '10962',
 '03981',
 '00133',
 '01915',
 '05292',
 '04622',
 '01757',
 '00059',
 '01715',
 '00467',
 '01230',
 '03052',
 '03525',
 '00974',
 '01971',
 '01196',
 '01670',
 '01612',
 '00492',
 '01351',
 '03330',
 '01540',
 '01259',
 '01300',
 '08940',
 '09009',
 '04095',
 '00235',
 '03997',
 '01146',
 '02295',
 '00058',
 '01275',
 '01173',
 '01765',
 '00660',
 '00186',
 '10974',
 '00804',
 '01999',
 '09002',
 '00973',
 '02457',
 '01751',
 '03165',
 '01231',
 '02160',
 '00404',
 '00438',
 '02995',
 '00409',
 '03494',
 '01938',
 '09030',
 '08596',
 '00453',
 '03315',
 '01052',
 '00336',
 '02855',
 '01589',
 '04660',
 '02865',
 '01618',
 '02888',
 '01195',
 '01388',
 '08971',
 '04004',
 '02476',
 '01038',
 '00735',
 '03056',
 '00874',
 '01632',
 '01616',
 '00669',
 '03248',
 '04645',
 '00937',
 '03073',
 '02207',
 '06024',
 '01462',
 '01634',
 '00579',
 '03142',
 '00364',
 '00898',
 '00208',
 '00875',
 '01064',
 '00032',
 '00902',
 '00572',
 '01015',
 '04137',
 '00924',
 '02869',
 '01243',
 '02776',
 '04621',
 '02421',
 '02321',
 '00993',
 '05966',
 '00376',
 '00836',
 '00938',
 '01655',
 '03074',
 '02071',
 '03488',
 '04084',
 '02020',
 '02818',
 '05118',
 '10989',
 '00772',
 '01101',
 '02880',
 '10986',
 '01063',
 '00708',
 '01596',
 '01749',
 '03395',
 '00563',
 '05339',
 '01850',
 '03461',
 '04753',
 '00727',
 '04071',
 '01866',
 '03373',
 '01073',
 '00303',
 '02839',
 '02848',
 '02291',
 '02505',
 '00475',
 '02049',
 '05316',
 '00841',
 '01000',
 '02409',
 '00553',
 '01710',
 '06055',
 '10978',
 '03311',
 '01402',
 '00873',
 '01125',
 '01502',
 '02052',
 '00440',
 '02962',
 '01511',
 '00893',
 '01873',
 '02180',
 '03347',
 '08922',
 '01693',
 '09004',
 '01860',
 '01339',
 '05100',
 '01689',
 '02388',
 '02938',
 '05965',
 '10970',
 '00991',
 '01396',
 '08920',
 '00967',
 '01271',
 '01910',
 '02567',
 '01575',
 '02972',
 '01561',
 '00765',
 '03978',
 '09000',
 '02877',
 '01098',
 '01628',
 '02675',
 '08995',
 '00302',
 '01785',
 '03338',
 '01517',
 '04011',
 '03436',
 '00764',
 '01429',
 '02215',
 '01510',
 '00943',
 '00510',
 '00108',
 '00566',
 '00653',
 '00701',
 '03333',
 '04052',
 '04638',
 '03019',
 '05132',
 '00851',
 '02380',
 '00822',
 '02475',
 '02398',
 '01237',
 '03510',
 '03397',
 '01246',
 '03394',
 '02702',
 '02251',
 '00866',
 '01049',
 '03411',
 '02832',
 '05988',
 '02178',
 '02760',
 '01162',
 '00236',
 '02654',
 '01087',
 '00174',
 '02032',
 '02154',
 '00505',
 '08989',
 '01221',
 '01261',
 '01925',
 '00632',
 '10964',
 '03098',
 '01035',
 '00126',
 '01448',
 '00434',
 '01081',
 '01536',
 '00348',
 '02190',
 '00219',
 '00958',
 '05153',
 '02384',
 '05999',
 '05121',
 '02765',
 '00770',
 '03724',
 '03487',
 '09038',
 '08983',
 '00019',
 '03317',
 '01389',
 '03715',
 '00031',
 '00957',
 '00054',
 '02750',
 '04641',
 '00327',
 '05106',
 '05958',
 '01818',
 '00159',
 '02125',
 '03541',
 '01845',
 '02093',
 '02500',
 '01180',
 '03565',
 '01118',
 '01238',
 '00090',
 '00215',
 '01361',
 '08994',
 '01734',
 '01043',
 '02075',
 '04629',
 '08917',
 '03548',
 '03392',
 '01848',
 '04018',
 '02950',
 '04182',
 '00650',
 '01996',
 '08914',
 '00092',
 '00678',
 '01807',
 '00796',
 '02858',
 '02929',
 '01705',
 '00927',
 '00768',
 '01521',
 '03544',
 '06030',
 '02028',
 '02269',
 '01973',
 '01579',
 '05718',
 '00202',
 '01422',
 '01929',
 '00268',
 '02350',
 '03324',
 '01552',
 '01214',
 '01952',
 '02340',
 '02819',
 '04072',
 '02517',
 '01309',
 '00446',
 '01427',
 '02781',
 '06049',
 '00681',
 '01359',
 '10981',
 '05310',
 '01066',
 '05341',
 '02999',
 '00035',
 '01585',
 '01656',
 '00237',
 '01431',
 '01832',
 '03552',
 '01492',
 '02992',
 '02584',
 '04671',
 '02292',
 '00849',
 '05981',
 '00013',
 '01647',
 '05721',
 '00049',
 '00925',
 '01371',
 '01992',
 '03137',
 '05723',
 '00946',
 '03296',
 '00117',
 '03503',
 '06040',
 '00756',
 '00655',
 '00730',
 '01253',
 '01468',
 '04634',
 '02808',
 '04690',
 '01786',
 '02936',
 '00787',
 '01577',
 '01285',
 '01593',
 '02941',
 '01321',
 '03332',
 '03240',
 '03225',
 '01144',
 '01346',
 '00987',
 '01278',
 '02470',
 '04664',
 '00387',
 '04174',
 '01053',
 '00961',
 '01446',
 '02908',
 '00887',
 '01384',
 '01767',
 '02823',
 '01433',
 '01699',
 '06063',
 '01737',
 '00862',
 '02013',
 '02900',
 '02912',
 '03310',
 '01383',
 '00288',
 '04619',
 '00368',
 '01849',
 '02097',
 '05209',
 '02370',
 '01122',
 '10967',
 '01459',
 '01268',
 '01244',
 '01592',
 '02437',
 '00547',
 '01692',
 '00221',
 '03048',
 '06032',
 '05323',
 '00699',
 '01056',
 '02345',
 '01149',
 '00692',
 '06729',
 '01674',
 '01685',
 '03483',
 '01210',
 '01290',
 '00528',
 '06047',
 '00248',
 '02933',
 '02015',
 '03361',
 '01193',
 '01266',
 '01711',
 '00815',
 '00430',
 '00628',
 '00562',
 '00432',
 '01023',
 '01819',
 '08904',
 '02795',
 '00560',
 '01233',
 '00767',
 '01170',
 '01672',
 '00293',
 '00709',
 '01415',
 '00552',
 '01537',
 '01659',
 '02189',
 '01452',
 '04074',
 '02976',
 '00607',
 '04016',
 '05989',
 '02892',
 '04657',
 '08969',
 '02153',
 '00539',
 '06724',
 '00258',
 '00682',
 '01329',
 '02035',
 '01828',
 '03454',
 '02674',
 '10995',
 '00250',
 '09008',
 '02054',
 '10975',
 '01197',
 '02803',
 '01716',
 '06182',
 '00930',
 '08984',
 '00096',
 '00536',
 '01436',
 '00646',
 '02844',
 '00298',
 '01719',
 '00175',
 '00337',
 '01497',
 '00647',
 '02631',
 '00761',
 '01265',
 ...}

In [ ]:
alldb_dp['PartitionKey'].replace({
'61':None,
'29':None,
'52':None,
'0083':None,
'000152':None,
'0034':None,
'23':None,
'219':None,
'185':None,
'00\u200b175':None,
'89':None,
'150':None,
'196':None,
'193':None,
'125':None,
'1881':None,
'32':None,
'124':None,
'112':None,
'00083\u200b':None,
'002.5':None                         
},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

## แก้คำข้อมูลที่ผิด

In [ ]:
set(alldb_dp['ov'])

{'0', '1', '2', '3', '4', 'ติดเชื้อ +2 '}

In [ ]:
alldb_dp['ov'].replace({'ติดเชื้อ +2':None,},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [ ]:
set(alldb_dp['title'])

{'Mrs',
 'ชาย',
 'ด.ช.',
 'ด.ญ.',
 'ด.ต.',
 'น',
 'น.ส',
 'น.ส ',
 'น.ส.',
 'นส',
 'นส.',
 'นส. ',
 'นาง',
 'นาง ',
 'นาง.',
 'นางl',
 'นางสาว',
 'นางสาว ',
 'นางสาว                   ',
 'นาน',
 'นาบ',
 'นาย',
 'นาย ',
 'นาย  ',
 'นาว',
 'นาวสาว',
 'นา่ง',
 'น่าย',
 'พจอ.',
 'พระ',
 'พระครุ',
 'พระปลัด',
 'พลฯ',
 'ร.ต.',
 'ร.ต.ต.',
 'ร.ต.ท.',
 'ร.ต.อ.',
 'ว่าที่ ร.ต.',
 'ว่าที่ ร.ท.',
 'ว่าที่ร้อยตรี',
 'ส.อ.',
 'ืนาง',
 'เด็กชาย',
 'เด็กหญิง'}

In [ ]:
alldb_dp['title'].replace({'นางสาว':'หญิง','นาง':'หญิง','นาย':'ชาย','น.ส.':'หญิง','นาย ':'ชาย','นส':'หญิง','ด.ญ.':'หญิง',
                                           'นาง ':'หญิง','ร.ต.ต.':'ไม่ปรากฏข้อมูล',' นาง':'หญิง',
                              '  นาง':'หญิง','ว่าที่ ร.ต.':'ไม่ปรากฏข้อมูล','นางl':'หญิง','ว่าที่ร้อยตรี':'ไม่ปรากฏข้อมูล',
                              'นส. ':'หญิง','พจอ.':'ไม่ปรากฏข้อมูล',
                              'น.ส ':'หญิง','พระ':'ชาย','Mrs':'หญิง','นา่ง':'หญิง',
                                           'นาย  ':'ชาย','น':'ไม่ปรากฏข้อมูล','ร.ต.':'ไม่ปรากฏข้อมูล','พระครุ':'ชาย','นาบ':'ชาย','นางสาว ':'หญิง','ชาย':'ชาย','ด.ต.':'ไม่ปรากฏข้อมูล',
                              'data is not completed':'ไม่ปรากฏข้อมูล','น่าย':'ชาย','เด็กชาย':'ชาย','นางสาว                   ':'หญิง','ว่าที่ ร.ท.':'ไม่ปรากฏข้อมูล','นาน':'ชาย','นาว':'หญิง',
                             ' นางสาว':'หญิง','ร.ต.ท.':'ไม่ปรากฏข้อมูล','นาง.':'หญิง','ด.ช.':'ชาย','เด็กหญิง':'หญิง', 'ืนาง':'หญิง','นาวสาว':'หญิง',
                               ' นาย':'ชาย','ส.อ.':'ไม่ปรากฏข้อมูล','พระปลัด':'ชาย','พลฯ':'ชาย','ร.ต.อ.':'ไม่ปรากฏข้อมูล','นส.':'หญิง','น.ส':'หญิง'}, inplace=True )

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [ ]:
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,age
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,หญิง,47
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,หญิง,41
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,หญิง,55
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,ชาย,66
195,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,หญิง,50
...,...,...,...,...,...,...,...,...,...,...,...
39416,26462,ieotqfnqcq.png,2022-03-22,Vivo 1920,11069,14-03-12,ปกติ (เหลืองใส),1,11003,หญิง,33
39417,26462,cywpeqziic.png,2022-03-21,Vivo 1920,11069,13-59-04,ปกติ (เหลืองใส),2,11005,ชาย,28
39418,26462,65DE7A37-62D2-4B7F-A494-89A89D5594A7,2022-03-22,"iPhone13,4",11069,13-41-47,ปกติ (เหลืองใส),2,11006,หญิง,72
39419,26462,85F0F443-D3B6-40DD-BD69-81C8D696E0DC,2022-03-21,"iPhone13,4",11069,14-17-46,ปกติ (เหลืองใส),0,11007,หญิง,48
39420,26462,vdxxgljykj.png,2022-03-21,Vivo V2050,11069,10-54-49,"ปกติ (เหลืองใส), ใส่เป็นน้ำเปล่า",1,11008,ชาย,36

# เตรียมข้อมูล hospital

In [ ]:
hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [ ]:
hospital.isnull().any()

hcode            False
name              True
zone_code        False
zone_name         True
provincecode      True
province         False
amphurcode        True
amphur            True
tamboncode        True
tambon            True
code4             True
name5             True
code9             True
name10            True
short_thai        True
short_english     True
dtype: bool

In [ ]:
hospital_dp = hospital.dropna()
hospital_dp

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
931,00933,โรงพยาบาลส่งเสริมสุขภาพตำบลสำโรงเหนือ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,2.0,สำโรงเหนือ,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
932,00934,โรงพยาบาลส่งเสริมสุขภาพตำบลบางเมือง,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
933,00935,โรงพยาบาลส่งเสริมสุขภาพตำบลเฉลิมพระเกียรติ บ้า...,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
934,00936,โรงพยาบาลส่งเสริมสุขภาพตำบลบางปูใหม่,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,8.0,บางปูใหม่,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
935,00937,โรงพยาบาลส่งเสริมสุขภาพตำบลแพรกษา,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,10.0,แพรกษา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [ ]:
hospital_dp.shape

(11798, 16)

In [ ]:
removes = hospital.shape[0] - hospital_dp.shape[0]
print(f'size before drop = {hospital.shape[0]}')
print(f'size after drop = {hospital_dp.shape[0]}')
print(f'% from drop = {(removes/hospital.shape[0])*100}')

size before drop = 17103
size after drop = 11798
% from drop = 31.017950067239664

## แทนข้อมูล fillna()

In [ ]:
hospital_c = hospital.fillna(value={'name':'ไม่ระบุ','zone_name':'ไม่ระบุ','amphur':'ไม่ระบุ','tambon':'ไม่ระบุ','name5':'ไม่ระบุ','name10':'ไม่ระบุ','short_thai':'ไม่ระบุ','short_english':'ไม่ระบุ'})
hospital_c

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,ไม่ระบุ,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,ไม่ระบุ,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,ไม่ระบุ,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,ไม่ระบุ,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,ไม่ระบุ,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

## แทนข้อมูลด้วย mean

In [ ]:
pc = hospital_c[['provincecode']].mean() 
hospital_c[['provincecode']] = hospital_c[['provincecode']].fillna(pc)

In [ ]:
ac = hospital_c[['amphurcode']].mean() 
hospital_c[['amphurcode']] = hospital_c[['amphurcode']].fillna(ac)

In [ ]:
tc = hospital_c[['tamboncode']].mean() 
hospital_c[['tamboncode']] = hospital_c[['tamboncode']].fillna(tc)

In [ ]:
c4 = hospital_c[['code4']].mean() 
hospital_c[['code4']] = hospital_c[['code4']].fillna(c4)

In [ ]:
c9 = hospital_c[['code9']].mean() 
hospital_c[['code9']] = hospital_c[['code9']].fillna(c9)

In [ ]:
hospital_c.isnull().any()

hcode            False
name             False
zone_code        False
zone_name        False
provincecode     False
province         False
amphurcode       False
amphur           False
tamboncode       False
tambon           False
code4            False
name5            False
code9            False
name10           False
short_thai       False
short_english    False
dtype: bool

In [ ]:
hospital_c1 = hospital_c [hospital_c['hcode']!= '2475x']

In [ ]:
hospital_c2 = hospital_c1 [hospital_c1['hcode']!= '2560x']

## hcode แค่ 5 หลักเพื่อเชื่อมตารางกับ alldb

In [ ]:
HS=list() 
for each_row in hospital_c2.iterrows(): 
    if len(str(each_row[1]['hcode']))== 5 : 
        if str(each_row[1]['hcode']) <= '99999' : 
          HS.append(True) 
        else: 
          HS.append(False)  
    else: 
          HS.append(False) 
hospital_c2 = hospital_c2[HS]
hospital_c2

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,รบ,RBR

In [ ]:
hospital_c2

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,10.84859,ไม่ระบุ,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.00000,1 ปฐมภูมิ,รบ,RBR

# รวมข้อมูล alldb กับ hospital ทั้งสองตารางเข้าด้วยกัน

In [ ]:
alldb_hos = alldb_dp.merge(hospital_c2,how='left',left_on='site',right_on='hcode') 
alldb_hos

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,หญิง,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
1,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,หญิง,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
2,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,หญิง,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
3,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,ชาย,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
4,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,หญิง,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37438,26462,ieotqfnqcq.png,2022-03-22,Vivo 1920,11069,14-03-12,ปกติ (เหลืองใส),1,11003,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37439,26462,cywpeqziic.png,2022-03-21,Vivo 1920,11069,13-59-04,ปกติ (เหลืองใส),2,11005,ชาย,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37440,26462,65DE7A37-62D2-4B7F-A494-89A89D5594A7,2022-03-22,"iPhone13,4",11069,13-41-47,ปกติ (เหลืองใส),2,11006,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37441,26462,85F0F443-D3B6-40DD-BD69-81C8D696E0DC,2022-03-21,"iPhone13,4",11069,14-17-46,ปกติ (เหลืองใส),0,11007,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37442,26462,vdxxgljykj.png,2022-03-21,Vivo V2050,11069,10-54-49,"ปกติ (เหลืองใส), ใส่เป็นน้ำเปล่า",1,11008,ชาย,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET

In [ ]:
alldb_hos.isnull().any()

user              True
RowKey           False
date             False
phone            False
site             False
time             False
urine            False
ov               False
PartitionKey     False
title            False
age              False
hcode            False
name             False
zone_code        False
zone_name        False
provincecode     False
province         False
amphurcode       False
amphur           False
tamboncode       False
tambon           False
code4            False
name5            False
code9            False
name10           False
short_thai       False
short_english    False
dtype: bool

In [ ]:
alldb_hosdp = alldb_hos.dropna()
alldb_hosdp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,title,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,หญิง,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
1,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,หญิง,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
2,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,หญิง,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
3,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,ชาย,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
4,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,หญิง,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37438,26462,ieotqfnqcq.png,2022-03-22,Vivo 1920,11069,14-03-12,ปกติ (เหลืองใส),1,11003,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37439,26462,cywpeqziic.png,2022-03-21,Vivo 1920,11069,13-59-04,ปกติ (เหลืองใส),2,11005,ชาย,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37440,26462,65DE7A37-62D2-4B7F-A494-89A89D5594A7,2022-03-22,"iPhone13,4",11069,13-41-47,ปกติ (เหลืองใส),2,11006,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37441,26462,85F0F443-D3B6-40DD-BD69-81C8D696E0DC,2022-03-21,"iPhone13,4",11069,14-17-46,ปกติ (เหลืองใส),0,11007,หญิง,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
37442,26462,vdxxgljykj.png,2022-03-21,Vivo V2050,11069,10-54-49,"ปกติ (เหลืองใส), ใส่เป็นน้ำเปล่า",1,11008,ชาย,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET

In [ ]:
alldb_hosdp.shape

(37442, 27)

In [ ]:
removes = alldb_hos.shape[0] - alldb_hosdp.shape[0]
print(f'size before drop = {alldb_hos.shape[0]}')
print(f'size after drop = {alldb_hosdp.shape[0]}')
print(f'% from drop = {(removes/alldb_hos.shape[0])*100}')

size before drop = 37443
size after drop = 37442
% from drop = 0.0026707261704457443

In [ ]:
alldb_hosdp.to_csv('dashb.csv', encoding='utf-8')

# Dashboard

https://datastudio.google.com/reporting/99a58b08-116e-4f1e-997d-cefd5dccfe8c